pari/app_pari/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,handler404,handler500
from app_pari import views

handler404 = 'pari.views.handler404'
handler500 = 'pari.views.handler500'

app_name = 'app_pari'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('',views.index,name='index'),
    path('sport', views.sport,name='sport'),
    path('details/<id>', views.details,name='details'),
    path('login',views.my_login,name='connect'),
    path('logout',views.my_logout,name='disconnect'),
    path('success',views.success,name='success'),
    path('lose',views.lose,name='lose'),
    path('choice',views.choice,name='choice'),
    #path('ligue',views.ligue,name='ligue'),
]

pari/pari/urls.py
from django.contrib import admin
from django.conf.urls import url,handler404,handler500
from pari import views
from django.urls import include,path
from app_pari import views as user_views
#from django.contrib.auth import views as auth_views

handler404 = 'pari.views.handler404'
handler500 = 'pari.views.handler500'

urlpatterns = [
    path('home/',views.home,name='home'),
    path('',views.home,name='home'),
    path('score/',views.score,name='score'),
    path('resultat/',views.resultat,name='resultat'),
    path('admin/', admin.site.urls),
    path('app_pari/',include('app_pari.urls')), #url application
    path('register/',user_views.register,name='register')
]

pari/templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!--MDB-->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.7/css/mdb.min.css" rel="stylesheet">
    <!--************************-->

    <title>BET.Sport</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <style type="text/css">
        @import url("https://fonts.googleapis.com/css?family=Marvel:400,700");
        @media (min-width: 800px) and (max-width: 850px) {
            .navbar:not(.top-nav-collapse) {
                background: #56BFB8 !important;
            }
        }
        body{
          background:-webkit-radial-gradient(circle,rgba(68, 3, 63, 0.623),rgba(68, 3, 63, 0.2));
          background:-o-radial-gradient(circle,rgba(68, 3, 63, 0.623),rgba(68, 3, 63, 0.2));
          background:-moz-radial-gradient(circle,rgba(68, 3, 63, 0.623),rgba(68, 3, 63, 0.2));
          background:radial-gradient(circle,rgba(68, 3, 63, 0.623),rgba(68, 3, 63, 0.2));

          color:black;
          font-family: "Marvel", sans-serif;
        }
      </style>
  </head>
  <body>
  {% include 'layout/nav.html' %}
  {% include 'layout/header.html' %}
  {% block content%}{% endblock  %}
  {% include 'layout/footer.html' %}

  <!-- MDB JS -->
  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.7/js/mdb.min.js"></script>
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>
</html>

pari/templates/layout/footer.html
<!-- Footer -->
<footer class="page-footer font-small grey  darken-3">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyrigt:
    <a href="#">Bet.SportS</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

pari/templates/layout/header.html
	<style>
		h2{  
			font-size: 8vh;
			text-align: center; 
			transform: translate(-50%, -50%);
		}
		[class^=char]{
			display: inline-block !important;
			position: relative;
			text-align: center;
			font-weight: bold;
		}
		.header{
			    background: -o-linear-gradient(rgba(67, 228, 27, 0.9),rgba(67, 228, 27,.4));
    			background: -webkit-linear-gradient(rgba(67, 228, 27, 0.9),rgba(67, 228, 27,.4));
    			background: -moz-linear-gradient(rgba(67, 228, 27, 0.9),rgba(67, 228, 27,.4));
    			background: linear-gradient(rgba(67, 228, 27, 0.9),rgba(67, 228, 27,.4))
				}

	</style>

<div class='header' style="margin-top:8vh;padding-bottom:20vh">
	<div class="container">
		<div class="row">
			<h2 style="margin-top:30vh;margin-left:85vh;"><div data-splitting>PARIEZ EN TOUTE SECURITE ! Bet.Sports</div></h2>
		</div>
	</div>
</div>

	<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.3/TweenMax.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://unpkg.com/splitting/dist/splitting.min.js"></script>

<script>
    // split text
Splitting(); // => letters are '<div>' wrapped!

// ref obj
var OBJ = 'h2 > div span';

// total nr of letters
var ntCh = OBJ.length;

// cos (index) => y
function curveY(i){
	var n = i / ntCh * 6.24;
	return (Math.cos(n)) * -200;
}

// sin (index) => x
function curveX(i){
	var n = i / ntCh * 6.24;
	return (Math.sin(n)) * -200;
}

// new timeline ref
var tl = new TimelineMax({delay:.5, repeat:-1 });

// color array helper
var arr = ["#008954","#0077be","#a9d046","#00b0f0","#a93056","#ee3338","#f89734","#ffd925","#973989","#cb92a6"];

// ZIGZAG letters 
tl.staggerFrom( OBJ , 1, {
	cycle:{ 
		y:curveY, 
	},
	x:-100, opacity:0
}, .03);
// ZIPPER letters
tl.staggerTo( OBJ , 3, { 
	cycle:{
		y:[-80, 80],
		color: arr,
		skewY:[ 20, -20],
		skewX:[ -20, 20],
	}, 
}, .05, "+=1" );

// sin curve out

tl.staggerTo( OBJ , 2, { 
	cycle: { 
		x: curveY,
		y: curveX, 
	},
	color: "#fff"
}, .03, "+=1" );
</script>

pari/templates/layout/nav.html
<nav class="navbar  fixed-top navbar-expand-lg navbar-light bg-light scrolling-navbar" style='margin-bottom:2px;'>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <!--<li class="nav-item">
        <a class="nav-link" href="{% url 'app_pari:sport' %}">Liste des paris</a>
      </li>-->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_pari:lose' %}">Resultat</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Pariez ici</a>
      </li>
    </ul>
  </div>
</nav>