pari/app_pari/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,handler404,handler500
from app_pari import views

handler404 = 'pari.views.handler404'
handler500 = 'pari.views.handler500'

app_name = 'app_pari'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('',views.index,name='index'),
    path('sport', views.sport,name='sport'),
    path('details/<id>', views.details,name='details'),
    path('login',views.my_login,name='connect'),
    path('logout',views.my_logout,name='disconnect'),
    path('success',views.success,name='success'),
    path('lose',views.lose,name='lose'),
    path('choice',views.choice,name='choice'),
    #path('ligue',views.ligue,name='ligue'),
]

pari/pari/urls.py
from django.contrib import admin
from django.conf.urls import url,handler404,handler500
from pari import views
from django.urls import include,path
from app_pari import views as user_views
#from django.contrib.auth import views as auth_views

handler404 = 'pari.views.handler404'
handler500 = 'pari.views.handler500'

urlpatterns = [
    path('home/',views.home,name='home'),
    path('',views.home,name='home'),
    path('score/',views.score,name='score'),
    path('resultat/',views.resultat,name='resultat'),
    path('admin/', admin.site.urls),
    path('app_pari/',include('app_pari.urls')), #url application
    path('register/',user_views.register,name='register')
]

pari/app_pari/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User

class AppPariUsers(models.Model):
    pseudo = models.CharField(max_length=50)
    profession = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'app_pari_users'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Ligue(models.Model):
    nom = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'ligue'


class Sport(models.Model):
    nom = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'sport'

pari/app_pari/views.py
from django.shortcuts import render,redirect
import datetime
from app_pari.api import Spot
from django.contrib.auth import authenticate , login ,logout
#from django.contrib.auth.forms import UserCreationForm #generateur de formulaire django
from django.contrib import messages #pour les messages de validation
# from app_pari.models import Users 

from django.contrib.auth.models import User
from django import forms
from django.template import RequestContext
import random


class Form_register(forms.Form):
    username= forms.CharField(label="username",max_length=100,required=True)
    first_name = forms.CharField(label="first_name",max_length=100,required=True)
    last_name = forms.CharField(label="last_name",max_length=100,required=True)
    email = forms.EmailField(label="email",max_length=100,required=True)
    password = forms.CharField(widget=forms.PasswordInput)

class Form_login(forms.Form):
    username= forms.CharField(label="username",max_length=100,required=True)
    password = forms.CharField(widget=forms.PasswordInput)

class Form_choice(forms.Form):
    ticket = forms.CharField(label="numero de ticket ici",max_length=5,required=True)
    


def handler404(request,exception):
    return render(request,'../errors/404.html',{},status=404)
def handler500(request):
    return render(request,'../errors/500.html',{},status=500)
    
    
 


def index(request):
    
    this_day = datetime.datetime.today().date()
    week_day = ['lundi','mardi','mercredi','jeudi','vendredi','samedi']
    return render(request,'app_pari/index.html',{'this_day': this_day,'week_day':week_day})

def sport(request):
    sports = Spot.all()
    return render(request,'app_pari/sport.html',{'sports': sports })

def details(request,id):
    #ligue = Ligue.found(id)
    sports = Spot.find(id)
    return render(request,'app_pari/details.html',{'sports':sports})

"""def ligue(request):
    ligue = Ligue.all()
    return render(request,'app_pari/ligue.html',{'ligue':ligue})"""

def success(request):
    g_ticket = mix()
    return render(request,'app_pari/success.html',{'g_ticket':g_ticket})
def lose(request):
    g_ticket = mix()
    return render(request,'app_pari/lose.html',{'g_ticket':g_ticket})
   
def register(request):
    form = Form_register()
    if request.method == 'POST':
        
        form = Form_register(request.POST)
        if form.is_valid():
            new_user = User(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['first_name'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password'],
                username=form.cleaned_data['username'],
            )
            new_user.save()
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            # message = messages.success(request,'inscription reussi pour {}'.format(new_user.username))
            return redirect('app_pari:connect')
        else:
            form = Form_register()
    return render(request,'app_pari/register.html',{'form':form})

#login
def my_login(request):
    if request.POST:
        #print('is post')
        form = Form_login(request.POST)
        if form.is_valid():
            #print('is valid')
            #print(form.cleaned_data['password'])
            user = authenticate(request=request,username=form.cleaned_data['username'],password=form.cleaned_data['password'])
            if user is not None:
                #print('is not none')
                login(request,user)
                return redirect('app_pari:sport')
            else:
                #print('is none')  
                return redirect('app_pari:connect')
                
        else:
            #print('is not valid')
            return redirect('app_pari:connect')
    else:
        #print('is not post')
        form = Form_login()
        return render(request,'app_pari/login.html',{'form':form})
#logout
def my_logout(request):
    logout(request)
    return redirect('home')  

def choice(request):
    if request.POST:
        form = Form_choice(request.POST)
        if form.is_valid():
            print('form valid')
            ticket = form.cleaned_data['ticket']
            g_ticket = mix()
            if ticket == g_ticket:
                print('success')
                return redirect('app_pari:success')
            else:
                #print('lose')
                return redirect('app_pari:lose')
        else:
            #print('not valid')
            return redirect('app_pari:choice')
    else:
        #print('not post')
        form = Form_choice()
        return render(request,'app_pari/choice.html',{'form':form})
        

#Generateur du chiffre aleatoire
def mix():
    lettre = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    chiffre = random.randint(10,99)
    alpha=random.sample(lettre,3)
    liste=list(str(chiffre))
    liste+=list(alpha)
    random.shuffle(liste)                  
    return ''.join(liste)


  
           
            
            
        
    
    
    
    

pari/app_pari/templates/app_pari/choice.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
  <h4 align='center'>Choix du numéro <h4>
  <p align='center'>Choisir un numero pour lancer voitre pari</p>

  <form method='post' action="{% url 'app_pari:choice' %}">
    {% csrf_token %}
      {{form | crispy }}
    <div align='center'>
      <button type="submit" class="btn btn-info">Lancer le pari</button>
    </div>
  </form>
</div>
{% endblock content %}

pari/app_pari/templates/app_pari/details.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <h4 align='center'> details du sport {{sports.id}}</h4>
    <h4 align='center'>Nom du sport : {{sports.nom}}</h4>
  
  <h4 align='center'>Choix du numéro <h4>
  <p align='center'>Choisir un numero pour lancer voitre pari</p>
</div>
{% endblock content %}
   

    
      

pari/app_pari/templates/app_pari/index.html
{% extends 'layout/base.html' %}
{% block content %}
<style>
  .list{
    list-style:none;
    font-size:2rem;
  }
  h5{
    margin-bottom:-1vh;
  }
</style>
    <h1 align='center'>Nous sommes le {{this_day}}</h1>
    <h5 align='center'>Voici les jours ou l'on peut parier </h5>
    <div align='center'>
      <ul class='list'>
        {% for days in week_day %}
        <li>{{days}}</li>
        {% endfor %}
      </ul>
    </div>
{% endblock content %}

pari/app_pari/templates/app_pari/ligue.html
{% extends 'layout/base.html' %}
{% block content %}
    {% for ligue in ligue %}
    
        {{ligue.nom}}
    
    {% endfor %}




{% endblock content %}

   

pari/app_pari/templates/app_pari/login.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post" action=" {% url 'app_pari:connect' %} " class="text-center border border-light p-5 animated zoomIn" style="background:lightgrey;padding:5vh;border-radius:10px;box-shadow:2px 2px 5px 10px black;">
    {% csrf_token %}

    <p class="h4 mb-4 text-primary">Connect</p>

    {{form | crispy }}

    <div class="d-flex justify-content-around">
        <div>
            
            <div class="custom-control custom-checkbox">
                <label class="custom-control-label" for="defaultLoginFormRemember">Se souvenir du mot de passe </label>
            </div>
        </div>
        <div>
           
            <a href="#">Mot de passe oublié ?</a>
        </div>
    </div>

    <button class="btn btn-info btn-block my-4" type="submit">Se connecter</button>
    <p>Not a member?
        <a href="#">Register</a>
    </p>

</form>
{% endblock content %}

pari/app_pari/templates/app_pari/lose.html
{% extends 'layout/base.html' %}
{% block content %}
<style>
.card{
    background: -o-linear-gradient(rgba(228,221,27,.7),rgba(228,221,27,.2));
    background: -webkit-linear-gradient(rgba(228,221,27,.7),rgba(228,221,27,.2));
    background: -moz-linear-gradient(rgba(228,221,27,.7),rgba(228,221,27,.2));
    background: linear-gradient(rgba(228,221,27,.7),rgba(228,221,27,.2))
}
</style>


            

<section class="card rgba-green-light wow flipInY">
    
    <div class="card-body text-center py-5 px-5 my-5">
        <h1 style='color:yellow'align='center'>OUPS ! vous avez perdu {{ request.user.username | upper }}</h1>
        <p style='color:black'align='center'>La perte endurer vous sera retirer directement sur votre compte bancaire<p>
        <h1 class="mb-4" style='color:black'>
            <strong>Nous esperions vous revoir, Merci et a Bientôt!</strong>
        </h1>
        <a href="{% url 'app_pari:disconnect' %}" class="btn btn-outline-yellow btn-lg" id="start">Se deconnecter
        </a>
    </div>
    
</section>

{% endblock content %}

pari/app_pari/templates/app_pari/register.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post" action="{% url 'register' %}" class="text-center border border-light p-5 animated zoomIn" style="background:lightgrey;padding:5vh;border-radius:10px;box-shadow:2px 2px 5px 10px black;">
    {% csrf_token %}

    <p class="h4 mb-4 text-primary">Remplir ce formulaire pour acceder a la plateforme de pari</p>

    {{form | crispy }}

    <div class="d-flex justify-content-around">
        <div>
            
            <div class="custom-control custom-checkbox">
                <label class="custom-control-label" for="defaultLoginFormRemember">Se souvenir du mot de passe </label>
            </div>
        </div>
        <div>
           
            <a href="#">Mot de passe oublié ?</a>
        </div>
    </div>

    <button class="btn btn-info btn-block my-4" type="submit">S'inscire</button>
    <p>Not a member?
        <a href="#">Register</a>
    </p>

</form>
{% endblock content %}

   

pari/app_pari/templates/app_pari/sport.html
{% extends 'layout/base.html' %}
{% block content %}

<style>
.card {
  position: relative;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column;
  background-color: #ffffff;
  border: 1px solid transparent;
  border-radius: 4px;
  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
  margin-bottom: 24px;
}
.card-block {
  -webkit-box-flex: 1;
  -webkit-flex: 1 1 auto;
      -ms-flex: 1 1 auto;
          flex: 1 1 auto;
    padding: 15px;
}
.card .card-block > p {
    padding-top: 4px;
    margin-bottom: 24px;
}
.card .card-block > p + p {
  margin-top: 8px;
  margin-bottom: 24px;
}
.card .card-block > p:last-of-type {
    margin-bottom: 8px;
}
.card-title {
  margin-top: 0;
  margin-bottom: 0;
  text-align: center;
}
.card-header {
  padding: 10px 15px;
  border-bottom: 1px solid transparent;
  border-top-right-radius: 3px;
  border-top-left-radius: 3px;
}
.card-footer {
  padding: 15px;
  background-color: #f5f5f5;
  border-top: none;
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
  text-align: center;
}
.card-footer > p {
    margin-bottom: 24px;
}
.card-footer > p:last-of-type {
     margin-bottom: 0px;
}
.card-success {
  background-color: #dff0d8;
  border-color: #d6e9c6;
}
.card-primary {
  background-color: #370749;
  border-color: #cccccc;
}
.card-primary .card-header {
  color: #ffffff;
  background-color: #370749;
  border-color: #cccccc;
}
.card-primary h1,
.card-primary h2,
.card-primary h3,
.card-primary h4,
.card-primary h5,
.card-primary h6,
.card-primary .h1,
.card-primary .h2,
.card-primary .h3,
.card-primary .h4,
.card-primary .h5,
.card-primary .h6 {
  color: #ffffff;
}
.card-primary .card-block {
    background-color: #fff;
}
</style>

  <h1 align='center' class='animated fadeInLeft'> Bienvenu(e) {{ request.user.username }}  ! </h1>
  <h1 align='center' class='animated fadeInRight'>Voici les differents sports a votre disposition</h1>
  {% for listage  in  sports %}
	<div class="container col-sm-6 animated fadeIn" style="margin-top:2vh;margin-left:53vh">
	        <div class="card card-primary">
	            <div class="card-header">
	                <h3 class="card-title">{{ listage.nom  }}</h3>
	            </div>
	            <div class="card-block">
	                <p style='margin-left:36vh;'>
                  <a href="choice" class='btn btn-outline-primary btn-lg'>Details</a>
                  </p>
	            </div>
	        </div>
	      </div>
  </div>
  {% endfor %}
  <h1 align='center'> Nombre de discipline disponible pour l'instant : {{sports | length}} </h1>
{% endblock content %}
   